language: csharp

env:
 - CONFIGS=Release

matrix:
  include:
    - os: linux
      mono: latest
      sudo: false
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none

script:
 - ./run -x tests
