language: csharp

env: CONFIGS=Release

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      mono: latest
    - os: linux
      sudo: required
      dist: trusty
      mono: none
      dotnet: 1.0.0-preview2-003121

script: ./run -x tests
