language: csharp

sudo: false

env:
 - CONFIGS=Release

matrix:
  include:
    - mono: latest
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none

script:
 - ./run -x tests
